### ISSUE TITLE
Missing license for the repo

### ISSUE THREAD

**Issue by kjellander-unity** [jackowild/aspnetcore-mocking-authorization#1]
Thanks for writing the excellent blog post at https://medium.com/@jackwild/bypassing-asp-net-core-2-0-authorize-tags-in-integration-tests-7bda8fcb0eca
I've been looking for a good way to integration test without endangering disabling authorization for a while.

I'd like to use small pieces of code from your GitHub project at https://github.com/jackowild/aspnetcore-bypassing-authentication but I noticed it's missing a license. Since I'm working for a company and this is for corporate use, I'd need you to add a license in order to do so (we take proper licensing seriously).

Could you just add something like MIT/BSD license to your project? It should be easy to do at GitHub.

**Comment by jackowild** [comment]
Done :)
